### ISSUE TITLE
Events don't appear in their proper place on the landing page based on their dates

### ISSUE THREAD

**Issue by benhur07b** [school-of-data/okf-events-a#5]
### Expected behavior
- The events inside `/events/` are ordered in the front page depending on their `date` front matter.
- When the website is rendered, it checks for the dates of the events and compares them to the current date. It then decides where to put the event in the front page of the website.
- Events with dates before the current date should be listed under  **OKF past events** list shown from **most recent to oldest.**
- All other events should be under the **OKF current and upcoming events** shown from *closest to farthest event date** except for events without dates which should go at the end of the said list.

### Current behavior
- Events with past dates do not automatically go to the OKF past events list.
- Events without dates go to the OKF past events list

### Possible Code in question
https://github.com/school-of-data/okf-events-a/blob/ccd33d979edb074c39290f5af47857b9cb618a5f/index.html#L7-L52

### Tests to pass
- [x] Add a new **event with date in the past**, it should go to **OKF past events** list in the landing page.
- [x] Add a new **event with date equals today**, it should go to **OKF current and upcoming events** list in the landing page.
- [x] Add a new **event with date in the future**, it should go to **OKF current and upcoming events** list in the landing page.
- [x] Add a new **event without a date**, it should go to **OKF current and upcoming events** list in the landing page.
- [x] Events in the **OKF past events** list should be from **most recent to oldest**.
- [x] Events in the **OKF current and upcoming events** list should be from **closest to farthest event date** (i.e. an event that is currently happening should appear before an event that will happen a month from now and the event that will happen a month from now should appear first than an event that will happen three months from now).
- [x] Events **without a date** should be at the **end of the OKF current and upcoming events** list.

### Alternative solution
Add a new list for events without a date so that there will be 3 lists in the front page.
- **OKF current and upcoming events** - those with current or future dates
- **OKF past/recent events** - those with past dates
- **OKF events being planned (?)** - those without dates

**Comment by benhur07b** [comment]
@nikeshbalami  When I run the website on local, it works as expected. So this might be an issue on the deployed version only. Might be worth checking out.

On local:
![image](https://user-images.githubusercontent.com/22940966/188753994-665b9e2c-06a1-434a-843d-47fa7de8c20f.png)

**Comment by benhur07b** [comment]
@nikeshbalami When I pushed a new event, the front page sorted itself out. This might be caused by some caching going on. The `.jekyll-cache` folder is suspect. 

In any case, please focus more on the behavior of events with no dates as it seems the website is working as intended for those with dates.

**Comment by nikeshbalami** [comment]
Alternative solution implemented via #9

**Comment by benhur07b** [comment]
> Alternative solution implemented via #9

Will review. Thanks!

**Comment by benhur07b** [comment]
Resolved by #9
