### ISSUE TITLE
Limit the number of events in the OKF past/recent events to 10

### ISSUE THREAD

**Issue by benhur07b** [school-of-data/okf-events-a#6]
### Expected behavior
- Only the 10 most recent events are shown in the OKF past/recent events list.
- Add a link at the bottom of the list to the events page (see #7 ).

### Current behavior
- All the past events are shown in the OKF past/recent events list.
- No button to the events page.

### Possible Code in question
https://github.com/school-of-data/okf-events-a/blob/ccd33d979edb074c39290f5af47857b9cb618a5f/index.html#L7-L52

### Tests to pass
- [x] Only the 10 most recent events are shown in the OKF past/recent events list.
- [x] Button links to the events page (see #7 ).

**Comment by nikeshbalami** [comment]
Implemented via #10, more enhancement is to be done based on the requirement of #7; currently, just an all-events page has been created.
